name: Build Geopandas Layer for AWS Glue

on:
  workflow_dispatch:

jobs:
  build-layer:
    runs-on: ubuntu-latest  # sin contenedor
    steps:
      - name: Instalar dependencias del sistema
        run: |
          sudo apt update
          sudo apt install -y python3-venv python3-dev g++ gcc gdal-bin libgdal-dev libproj-dev libgeos-dev zip

      - name: Crear entorno virtual e instalar geopandas
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install geopandas

      - name: Empaquetar site-packages
        run: |
          cd venv/lib/python3.*/site-packages
          zip -r9 ../../../../geopandas_layer.zip .

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: geopandas_layer
          path: geopandas_layer.zip
